### ISSUE TITLE
About baseline accuracy & training 6Conv, 2FC model 

### ISSUE THREAD

**Issue by mountains-high** [Intelligent-Computing-Lab-Yale/Exploring-Lottery-Ticket-Hypothesis-in-Sparse-SNNs#1]
Hello, 

Thanks for the great work and code sharing! 
Is it possible for you to share the training for acquainting the baseline accuracies for these 3 models in Table 2? (Mainly Conv, FC, and ResNet19 model)

![image](https://user-images.githubusercontent.com/82306310/191176733-4db8fa7a-7bd0-4bf7-8322-c37eff63b0f3.png)

Thank you for your consideration.

**Comment by lotusroot-kim** [comment]
Hi thanks for your question!

Chen et al. provided code on GitHub. You can refer to their code.

For ours, you can use the ResNet19 model.

Let me know if you have further questions.

**Comment by mountains-high** [comment]
Thank you
